package vista;

import controlador.Reportes;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

/**
 *
 * @author andre
 */
public class FrmMenu extends javax.swing.JFrame {

    public static JDesktopPane jDesktopPane_menu;
    // Constructor del formulario
    public FrmMenu() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("UNIVERSAL TRADE");
        this.setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
        this.setLayout(null);
        jDesktopPane_menu = new JDesktopPane();
        // Configuración del JDesktopPane
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_menu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Menu_nuevoUsuario = new javax.swing.JMenuItem();
        Menu_gestionarUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Menu_nuevoProducto = new javax.swing.JMenuItem();
        Menu_gestionarProducto = new javax.swing.JMenuItem();
        Menu_actualizarStock = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Menu_nuevoCliente = new javax.swing.JMenuItem();
        Menu_gestionarCliente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Menu_nuevaCategoria = new javax.swing.JMenuItem();
        Menu_gestionarCategoria = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Menu_nuevaVenta = new javax.swing.JMenuItem();
        Menu_gestionarVenta = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        Menu_reportesClientes = new javax.swing.JMenuItem();
        Menu_reportesCategorias = new javax.swing.JMenuItem();
        Menu_reportesProductos = new javax.swing.JMenuItem();
        Menu_reportesVentas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        Menu_verHistorial = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        Menu_cerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMenu1.setText("Usuario");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(150, 50));

        Menu_nuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_nuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        Menu_nuevoUsuario.setText("Nuevo Usuario");
        Menu_nuevoUsuario.setPreferredSize(new java.awt.Dimension(180, 30));
        Menu_nuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_nuevoUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_nuevoUsuario);

        Menu_gestionarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_gestionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        Menu_gestionarUsuario.setText("Gestionar Usuarios");
        Menu_gestionarUsuario.setPreferredSize(new java.awt.Dimension(180, 30));
        Menu_gestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_gestionarUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_gestionarUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenu2.setText("Producto");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        Menu_nuevoProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_nuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-producto.png"))); // NOI18N
        Menu_nuevoProducto.setText("Nuevo Producto");
        Menu_nuevoProducto.setPreferredSize(new java.awt.Dimension(200, 30));
        Menu_nuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_nuevoProductoActionPerformed(evt);
            }
        });
        jMenu2.add(Menu_nuevoProducto);

        Menu_gestionarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_gestionarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        Menu_gestionarProducto.setText("Gestionar Productos");
        Menu_gestionarProducto.setPreferredSize(new java.awt.Dimension(200, 30));
        Menu_gestionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_gestionarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(Menu_gestionarProducto);

        Menu_actualizarStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_actualizarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        Menu_actualizarStock.setText("Actualizar Stock");
        Menu_actualizarStock.setPreferredSize(new java.awt.Dimension(200, 30));
        Menu_actualizarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_actualizarStockActionPerformed(evt);
            }
        });
        jMenu2.add(Menu_actualizarStock);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenu3.setText("Cliente");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(150, 50));

        Menu_nuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_nuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        Menu_nuevoCliente.setText("Nuevo Cliente");
        Menu_nuevoCliente.setPreferredSize(new java.awt.Dimension(180, 30));
        Menu_nuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_nuevoClienteActionPerformed(evt);
            }
        });
        jMenu3.add(Menu_nuevoCliente);

        Menu_gestionarCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_gestionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        Menu_gestionarCliente.setText("Gestionar Clientes");
        Menu_gestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_gestionarClienteActionPerformed(evt);
            }
        });
        jMenu3.add(Menu_gestionarCliente);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenu4.setText("Categoria");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 50));

        Menu_nuevaCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_nuevaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        Menu_nuevaCategoria.setText("Nueva Categoria");
        Menu_nuevaCategoria.setPreferredSize(new java.awt.Dimension(200, 30));
        Menu_nuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_nuevaCategoriaActionPerformed(evt);
            }
        });
        jMenu4.add(Menu_nuevaCategoria);

        Menu_gestionarCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_gestionarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        Menu_gestionarCategoria.setText("Gestionar Categorias");
        Menu_gestionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_gestionarCategoriaActionPerformed(evt);
            }
        });
        jMenu4.add(Menu_gestionarCategoria);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        jMenu5.setText("Facturar");
        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(150, 50));

        Menu_nuevaVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_nuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        Menu_nuevaVenta.setText("Nueva Venta");
        Menu_nuevaVenta.setPreferredSize(new java.awt.Dimension(200, 30));
        Menu_nuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_nuevaVentaActionPerformed(evt);
            }
        });
        jMenu5.add(Menu_nuevaVenta);

        Menu_gestionarVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_gestionarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        Menu_gestionarVenta.setText("Gestionar Ventas");
        Menu_gestionarVenta.setPreferredSize(new java.awt.Dimension(200, 30));
        Menu_gestionarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_gestionarVentaActionPerformed(evt);
            }
        });
        jMenu5.add(Menu_gestionarVenta);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes.png"))); // NOI18N
        jMenu6.setText("Reportes");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 50));

        Menu_reportesClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_reportesClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        Menu_reportesClientes.setText("Reportes Clientes");
        Menu_reportesClientes.setPreferredSize(new java.awt.Dimension(200, 30));
        Menu_reportesClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_reportesClientesActionPerformed(evt);
            }
        });
        jMenu6.add(Menu_reportesClientes);

        Menu_reportesCategorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_reportesCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        Menu_reportesCategorias.setText("Reportes Categorias");
        Menu_reportesCategorias.setPreferredSize(new java.awt.Dimension(200, 30));
        Menu_reportesCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_reportesCategoriasActionPerformed(evt);
            }
        });
        jMenu6.add(Menu_reportesCategorias);

        Menu_reportesProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_reportesProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        Menu_reportesProductos.setText("Reportes Productos");
        Menu_reportesProductos.setPreferredSize(new java.awt.Dimension(200, 30));
        Menu_reportesProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_reportesProductosActionPerformed(evt);
            }
        });
        jMenu6.add(Menu_reportesProductos);

        Menu_reportesVentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_reportesVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        Menu_reportesVentas.setText("Reportes Ventas");
        Menu_reportesVentas.setPreferredSize(new java.awt.Dimension(200, 30));
        Menu_reportesVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_reportesVentasActionPerformed(evt);
            }
        });
        jMenu6.add(Menu_reportesVentas);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        jMenu7.setText("Historial");
        jMenu7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(150, 50));

        Menu_verHistorial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_verHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        Menu_verHistorial.setText("Ver Historial");
        Menu_verHistorial.setPreferredSize(new java.awt.Dimension(150, 30));
        Menu_verHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_verHistorialActionPerformed(evt);
            }
        });
        jMenu7.add(Menu_verHistorial);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu8.setText("Cerrar Sesión");
        jMenu8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(200, 50));

        Menu_cerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Menu_cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        Menu_cerrarSesion.setText("Cerrar Sesión");
        Menu_cerrarSesion.setPreferredSize(new java.awt.Dimension(150, 30));
        Menu_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_cerrarSesionActionPerformed(evt);
            }
        });
        jMenu8.add(Menu_cerrarSesion);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_gestionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_gestionarCategoriaActionPerformed
        InterGestionarCategoria interGestionarCategoria = new InterGestionarCategoria();
        jDesktopPane_menu.add(interGestionarCategoria);
        interGestionarCategoria.setVisible(true);
    }//GEN-LAST:event_Menu_gestionarCategoriaActionPerformed

    private void Menu_nuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_nuevaCategoriaActionPerformed
        InterCategoria interCategoria = new InterCategoria();
        jDesktopPane_menu.add(interCategoria);
        interCategoria.setVisible(true);
    }//GEN-LAST:event_Menu_nuevaCategoriaActionPerformed

    private void Menu_nuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_nuevoProductoActionPerformed
        InterProducto interProducto = new InterProducto();
        jDesktopPane_menu.add(interProducto);
        interProducto.setVisible(true);
    }//GEN-LAST:event_Menu_nuevoProductoActionPerformed

    private void Menu_gestionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_gestionarProductoActionPerformed
        InterGestionarProducto interGestionarProducto = new InterGestionarProducto();
        jDesktopPane_menu.add(interGestionarProducto);
        interGestionarProducto.setVisible(true);
    }//GEN-LAST:event_Menu_gestionarProductoActionPerformed

    private void Menu_nuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_nuevoClienteActionPerformed
        InterCliente interCliente = new InterCliente();
        jDesktopPane_menu.add(interCliente);
        interCliente.setVisible(true);
    }//GEN-LAST:event_Menu_nuevoClienteActionPerformed

    private void Menu_gestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_gestionarClienteActionPerformed
        InterGestionarCliente interGestionarCliente = new InterGestionarCliente();
        jDesktopPane_menu.add(interGestionarCliente);
        interGestionarCliente.setVisible(true);
    }//GEN-LAST:event_Menu_gestionarClienteActionPerformed

    private void Menu_actualizarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_actualizarStockActionPerformed
        InterActualizarStock interActualizarStock = new InterActualizarStock();
        jDesktopPane_menu.add(interActualizarStock);
        interActualizarStock.setVisible(true);
    }//GEN-LAST:event_Menu_actualizarStockActionPerformed

    private void Menu_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_cerrarSesionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Menu_cerrarSesionActionPerformed

    private void Menu_nuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_nuevoUsuarioActionPerformed
        InterUsuario interUsuario = new InterUsuario();
        jDesktopPane_menu.add(interUsuario);
        interUsuario.setVisible(true);
    }//GEN-LAST:event_Menu_nuevoUsuarioActionPerformed

    private void Menu_gestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_gestionarUsuarioActionPerformed
        InterGestionarUsuario interGestionarUsuario = new InterGestionarUsuario();
        jDesktopPane_menu.add(interGestionarUsuario);
        interGestionarUsuario.setVisible(true);
    }//GEN-LAST:event_Menu_gestionarUsuarioActionPerformed

    private void Menu_nuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_nuevaVentaActionPerformed
        InterFacturacion interFacturacion = new InterFacturacion();
        jDesktopPane_menu.add(interFacturacion);
        interFacturacion.setVisible(true);
    }//GEN-LAST:event_Menu_nuevaVentaActionPerformed

    private void Menu_gestionarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_gestionarVentaActionPerformed
        InterGestionarVentas interGestionarVentas = new InterGestionarVentas();
        jDesktopPane_menu.add(interGestionarVentas);
        interGestionarVentas.setVisible(true);
    }//GEN-LAST:event_Menu_gestionarVentaActionPerformed

    private void Menu_reportesClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_reportesClientesActionPerformed
        Reportes reporte = new Reportes();
        reporte.ReporteClientes();
    }//GEN-LAST:event_Menu_reportesClientesActionPerformed

    private void Menu_reportesProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_reportesProductosActionPerformed
        Reportes reporte = new Reportes();
        reporte.ReporteProductos();
    }//GEN-LAST:event_Menu_reportesProductosActionPerformed

    private void Menu_reportesCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_reportesCategoriasActionPerformed
        Reportes reporte = new Reportes();
        reporte.ReporteCategorias();
    }//GEN-LAST:event_Menu_reportesCategoriasActionPerformed

    private void Menu_reportesVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_reportesVentasActionPerformed
        Reportes reporte = new Reportes();
        reporte.ReporteVentas();
    }//GEN-LAST:event_Menu_reportesVentasActionPerformed

    private void Menu_verHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_verHistorialActionPerformed
        InterGraficas interGraficas = new InterGraficas();
        jDesktopPane_menu.add(interGraficas);
        interGraficas.setVisible(true);
    }//GEN-LAST:event_Menu_verHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu_actualizarStock;
    private javax.swing.JMenuItem Menu_cerrarSesion;
    private javax.swing.JMenuItem Menu_gestionarCategoria;
    private javax.swing.JMenuItem Menu_gestionarCliente;
    private javax.swing.JMenuItem Menu_gestionarProducto;
    private javax.swing.JMenuItem Menu_gestionarUsuario;
    private javax.swing.JMenuItem Menu_gestionarVenta;
    private javax.swing.JMenuItem Menu_nuevaCategoria;
    private javax.swing.JMenuItem Menu_nuevaVenta;
    private javax.swing.JMenuItem Menu_nuevoCliente;
    private javax.swing.JMenuItem Menu_nuevoProducto;
    private javax.swing.JMenuItem Menu_nuevoUsuario;
    private javax.swing.JMenuItem Menu_reportesCategorias;
    private javax.swing.JMenuItem Menu_reportesClientes;
    private javax.swing.JMenuItem Menu_reportesProductos;
    private javax.swing.JMenuItem Menu_reportesVentas;
    private javax.swing.JMenuItem Menu_verHistorial;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
